name: 'GitHub Actions pull'

on:
  push:
    branches: 
      - master
  schedule:
   - cron: '0,30 * * * *'
jobs:
  jdbot_pull:
    runs-on: ubuntu-latest
    steps:
      - name: set_time
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'clone dust'
        run: |
          rm -rf dust
          git clone https://github.com/monk-coder/dust.git
          ls dust
          cd dust 
          rm -rf .git 
          rm README.md
          echo "=================="
          \cp -r ./* ../
          cd ..
          ls dust
          # \mv dust ./old/dust$(date +%Y%m%d%H%M%S)
          echo "# 更新时间⌚️ 
          > $(date +%Y%m%d%H%M%S)" > README.md
      - name: "clone NobyDa"
        run: |
          rm -rf NobyDa
          git clone -b master https://github.com/NobyDa/Script.git
          cd Script 
          rm -rf .git 
          rm README.md
          echo "=================="
          #\cp -r ./* ../NobyDa
          \cp -r ./iQIYI-DailyBonus/iQIYI.js ../i-chenzhe
          cd ..
          \mv Script NobyDa
          # \mv dust ./old/dust$(date +%Y%m%d%H%M%S)
          echo "# 更新时间⌚️ 
          > $(date +%Y%m%d%H%M%S)" > README.md
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "$(date +%Y%m%d%H%M%S)" -a
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
      - name: 'Create a Release'
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          args: scripts