name: Manage_WXRobot_Web
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Manage_WXRobot_Web
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Manage_WXRobot_Web
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/xiaorui16888/Manage_WXRobot_Web.git"
          source_branch: "main"
          destination_branch: "Manage_WXRobot_Web"
          github_token: ${{ secrets.PAT }}
